-- Plugins
require("plugins")
-- Configs
require("configs.general")
require("configs.color-scheme")
require("configs.lualine")
require("configs.vim-startify")
require("configs.nvim-tree")
require("configs.telescope")
require("configs.neoscroll")
require("configs.vim-floaterm")
require("configs.treesitter")
require("configs.coq-nvim")
require("configs.nvim-lspconfig")
require("configs.formatter")
require("configs.kommentary")
require("configs.indent-blankline")
require("configs.nvim-colorizer")
require("configs.autopairs")
require("configs.nvim-treesitter-context")
require("configs.vim-test")
require("configs.vimspector")
-- Mappings
require("mappings")
